### ISSUE TITLE
Incorrect error response in novaposhta/client.py, line 157

### ISSUE THREAD

**Issue by SergeyTadlya** [semolex/novaposhta-api-client#12] opened 2024-09-26 21:29 UTC
@semolex @krasnoukhov @Melistraza 

Hello, the error response is incorrectly specified in the file `novaposhta/client.py, line 157`
here
` error = response["errors"][0]`

Is the format in which the Nova Poshta api returns the error
`"errors": {
        "some_order_id": "Error getting payment info ttn",
        "0": "No document changed DeletionMark"
    }`
    
0 is the text value of the key, not the element index because otherwise it returns `KeyError: 0`. Please fix it.

**Comment by semolex** [comment] 2024-09-27 05:24
> @semolex @krasnoukhov @Melistraza
> 
> Hello, the error response is incorrectly specified in the file `novaposhta/client.py, line 157` here ` error = response["errors"][0]`
> 
> Is the format in which the Nova Poshta api returns the error `"errors": { "some_order_id": "Error getting payment info ttn", "0": "No document changed DeletionMark" }`
> 
> 0 is the text value of the key, not the element index because otherwise it returns `KeyError: 0`. Please fix it.

On it, thanks

**Comment by semolex** [comment] 2024-09-27 10:23
> @semolex @krasnoukhov @Melistraza
> 
> Hello, the error response is incorrectly specified in the file `novaposhta/client.py, line 157` here ` error = response["errors"][0]`
> 
> Is the format in which the Nova Poshta api returns the error `"errors": { "some_order_id": "Error getting payment info ttn", "0": "No document changed DeletionMark" }`
> 
> 0 is the text value of the key, not the element index because otherwise it returns `KeyError: 0`. Please fix it.

As of now errors are arsed correctly (at least for test example):
```python
async def use_api_async():
    with NovaPoshtaApi('MY_TOKEN', timeout=30, async_mode=True, raise_for_errors=True) as async_client:
        address = async_client.address
        settlements = await address.search_settlements(city_name='!Київ', limit=5)
        print(settlements)
asyncio.run(use_api_async())
```
I am trying to find inconsistent APIs responsible for different API error structure

**Comment by semolex** [comment] 2024-09-27 10:28
This is the format I receive:
```python
{'success': False, 'data': [], 'errors': ['API key incorrect'], 'warnings': [], 'info': [], 'messageCodes': [], 'errorCodes': [], 'warningCodes': [], 'infoCodes': []}
```

**Comment by semolex** [comment] 2024-09-27 10:41
@SergeyTadlya Please provide a method and code example which produced this kind of error

**Comment by SergeyTadlya** [comment] 2024-09-27 11:08
> @SergeyTadlya Please provide a method and code example which produced this kind of error

code
![screen](https://github.com/user-attachments/assets/716bf145-b518-49bf-a5e7-b7c6811afe40)

in response i have 500 error

 `File "D:\Frameworks\django_for_test\.venv\Lib\site-packages\novaposhta\client.py", line 82, in _send_sync`
    `return self._maybe_check_errors(response.json())`
           `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "D:\Frameworks\django_for_test\.venv\Lib\site-packages\novaposhta\client.py", line 157, in _maybe_check_errors
    error = response["errors"][0]`
            `~~~~~~~~~~~~~~~~~~^^^`
`KeyError: 0`

**Comment by semolex** [comment] 2024-09-27 11:13
> > @SergeyTadlya Please provide a method and code example which produced this kind of error
> 
> code ![screen](https://private-user-images.githubusercontent.com/118724165/371506417-716bf145-b518-49bf-a5e7-b7c6811afe40.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzU2NTYsIm5iZiI6MTcyNzQzNTM1NiwicGF0aCI6Ii8xMTg3MjQxNjUvMzcxNTA2NDE3LTcxNmJmMTQ1LWI1MTgtNDliZi1hNWU3LWI3YzY4MTFhZmU0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMTA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWNiZTZhMGE5MGJhODBhMzEzZjBkNWViMGY5YTg4OWQ2MjBjNDFlZDg0ZGRmYzk5ZDQ5ZDc5NDljM2U5ZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0XwU8KcR8GU4E21jTW4a2FramUYj6oR-lBwx9-dhwRg)
> 
> in response i have 500 error
> 
> `File "D:\Frameworks\django_for_test\.venv\Lib\site-packages\novaposhta\client.py", line 82, in _send_sync` `return self._maybe_check_errors(response.json())` `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^` `File "D:\Frameworks\django_for_test\.venv\Lib\site-packages\novaposhta\client.py", line 157, in _maybe_check_errors error = response["errors"][0]` `~~~~~~~~~~~~~~~~~~^^^` `KeyError: 0`

Very strange
```python
client = NovaPoshtaApi('API_TOKEN', timeout=30, raise_for_errors=True)
internet_document = client.internet_document
internet_document.delete('00000000-0000-0000-0000-000000000000')
```
raises:
```
  File "******/novaposhta/client.py", line 161, in _maybe_check_errors
    raise APIRequestError(error)
novaposhta.client.APIRequestError: No document changed DeletionMark
```
UPD:
Full response is:
```python
{'success': False, 'data': [], 'errors': ['No document changed DeletionMark'], 'warnings': [], 'info': [], 'messageCodes': [], 'errorCodes': ['20000201173'], 'warningCodes': [], 'infoCodes': []}
```

**Comment by SergeyTadlya** [comment] 2024-09-27 11:24
> Very strange
> 
> ```python
> client = NovaPoshtaApi('API_TOKEN', timeout=30, raise_for_errors=True)
> internet_document = client.internet_document
> internet_document.delete('00000000-0000-0000-0000-000000000000')
> ```
> 
> raises:
> 
> ```
>   File "******/novaposhta/client.py", line 161, in _maybe_check_errors
>     raise APIRequestError(error)
> novaposhta.client.APIRequestError: No document changed DeletionMark
> ```
> 
> UPD: Full response is:
> 
> ```python
> {'success': False, 'data': [], 'errors': ['No document changed DeletionMark'], 'warnings': [], 'info': [], 'messageCodes': [], 'errorCodes': ['20000201173'], 'warningCodes': [], 'infoCodes': []}
> ```

This is what the request and response look like when I make a request on the Nova Poshta api

![screen_2](https://github.com/user-attachments/assets/424f3519-ca3b-4cc9-a9ee-f9acdd954a8d)

**Comment by semolex** [comment] 2024-09-27 11:42
> > Very strange
> > ```python
> > client = NovaPoshtaApi('API_TOKEN', timeout=30, raise_for_errors=True)
> > internet_document = client.internet_document
> > internet_document.delete('00000000-0000-0000-0000-000000000000')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > raises:
> > ```
> >   File "******/novaposhta/client.py", line 161, in _maybe_check_errors
> >     raise APIRequestError(error)
> > novaposhta.client.APIRequestError: No document changed DeletionMark
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > UPD: Full response is:
> > ```python
> > {'success': False, 'data': [], 'errors': ['No document changed DeletionMark'], 'warnings': [], 'info': [], 'messageCodes': [], 'errorCodes': ['20000201173'], 'warningCodes': [], 'infoCodes': []}
> > ```
> 
> This is what the request and response look like when I make a request on the Nova Poshta api
> 
> ![screen_2](https://private-user-images.githubusercontent.com/118724165/371511796-424f3519-ca3b-4cc9-a9ee-f9acdd954a8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzY4NzksIm5iZiI6MTcyNzQzNjU3OSwicGF0aCI6Ii8xMTg3MjQxNjUvMzcxNTExNzk2LTQyNGYzNTE5LWNhM2ItNGNjOS1hOWVlLWY5YWNkZDk1NGE4ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMTI5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDFjYmE5NjM3YmQ4OTIzYjA2YTA1NzEwMTliZGRiOWY5M2Y3Zjc4MjY2OWEzYjU0ZTI1MDYwZGU1MjdjMDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KIsEIRbAjZwT5GDELpdc2zw776vFNfZnCIWk50QOD0s)

![Screenshot 2024-09-27 at 14 38 31](https://github.com/user-attachments/assets/b3444dc7-8bbb-4799-add6-9ed446d55b4d)
I am still not able to reproduce this error.
I will add code that will handle this indeed, but for now I cannot understand why you have a different response.I also tried to reproduce multiple errors, they are still returned as array
![Screenshot 2024-09-27 at 14 41 30](https://github.com/user-attachments/assets/ac8f7a2b-7778-466c-8ad8-3b07b4e0fa4d)

**Comment by semolex** [comment] 2024-09-27 11:55
Fixed as of
https://github.com/semolex/novaposhta-python-client/pull/13
Preparing release

**Comment by semolex** [comment] 2024-09-27 11:59
@SergeyTadlya Please try to bump dependency to v0.1.9

**Closed as completed** 2024-09-27 15:13 UTC
